---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ejonaco/public_html
    # Copy all website files (excluding dev files)
    - /bin/cp -R index.html $DEPLOYPATH/
    - /bin/cp -R about.html $DEPLOYPATH/
    - /bin/cp -R contact.html $DEPLOYPATH/
    - /bin/cp -R partner.html $DEPLOYPATH/
    - /bin/cp -R products.html $DEPLOYPATH/
    - /bin/cp -R projects.html $DEPLOYPATH/
    - /bin/cp -R services.html $DEPLOYPATH/
    - /bin/cp -R robots.txt $DEPLOYPATH/
    - /bin/cp -R sitemap.xml $DEPLOYPATH/
    - /bin/cp -R css $DEPLOYPATH/
    - /bin/cp -R js $DEPLOYPATH/
    - /bin/cp -R images $DEPLOYPATH/
    - /bin/cp -R content $DEPLOYPATH/
    - /bin/cp -R admin $DEPLOYPATH/
